<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit; }
$result = isset( $page_data ) && is_array( $page_data ) ? $page_data : array();
?>
<section class="mt-hnb" data-hotel-booking><p class="mt-hotel-eyebrow">Operación</p><h1>Nueva reserva</h1><p>La tarifa y la disponibilidad se calculan en tiempo real con el motor oficial de MeTransfers.</p>
<?php
if ( ! empty( $result['error'] ) ) :
	?>
	<div class="mt-hotel-alert"><?php echo esc_html( $result['error'] ); ?></div><?php endif; ?>
<?php
if ( ! empty( $result['success'] ) ) :
	?>
	<div class="mt-hotel-alert mt-hotel-alert--success"><?php echo esc_html( $result['success'] ); ?> <a href="<?php echo esc_url( \MeTransfers\HotelPortal\Routing\Router::url( 'bookings' ) ); ?>">Ver reservas</a></div><?php endif; ?>
<form method="post" class="mt-hotel-form-grid" data-booking-form><?php wp_nonce_field( \MeTransfers\HotelPortal\Services\HotelOperations::NONCE_ACTION, 'mt_operations_nonce' ); ?><input type="hidden" name="mt_create_booking" value="1"><input type="hidden" name="vehicle_id" data-vehicle-id><input type="hidden" name="quoted_price_cents" data-quoted-price>
<div class="mt-hotel-phase-card mt-hotel-field--full"><h2>1. Trayecto</h2><div class="mt-hnb-trip-type"><label><input type="radio" name="trip_type" value="one_way" checked> Sólo ida</label> <label><input type="radio" name="trip_type" value="round_trip"> Ida y vuelta</label></div>
<div class="mt-hotel-form-grid"><div class="mt-hotel-field"><label for="mt-booking_date">Fecha</label><input id="mt-booking_date" name="booking_date" type="date" required></div><div class="mt-hotel-field"><label for="mt-booking_time">Hora</label><input id="mt-booking_time" name="booking_time" type="time" required></div>
<div class="mt-hotel-field"><label for="mt-origin">Origen</label><div class="mt-hnb-input-row"><input id="mt-origin" name="origin" type="text" autocomplete="off" required><button type="button" class="mt-hnb-hotel-shortcut" data-hotel-fill="origin">Mi hotel</button></div></div><div class="mt-hotel-field"><label for="mt-destination">Destino</label><div class="mt-hnb-input-row"><input id="mt-destination" name="destination" type="text" autocomplete="off" required><button type="button" class="mt-hnb-hotel-shortcut" data-hotel-fill="destination">Mi hotel</button></div></div></div>
<div data-return-fields hidden><div class="mt-hotel-form-grid"><div class="mt-hotel-field"><label for="mt-return_date">Fecha de vuelta</label><input id="mt-return_date" name="return_date" type="date"></div><div class="mt-hotel-field"><label for="mt-return_time">Hora de vuelta</label><input id="mt-return_time" name="return_time" type="time"></div><div class="mt-hotel-field"><label for="mt-return_origin">Origen de vuelta</label><input id="mt-return_origin" name="return_origin" type="text" autocomplete="off"></div><div class="mt-hotel-field"><label for="mt-return_destination">Destino de vuelta</label><input id="mt-return_destination" name="return_destination" type="text" autocomplete="off"></div></div></div>
<div class="mt-hotel-form-grid"><div class="mt-hotel-field"><label for="mt-passengers">Pasajeros</label><input id="mt-passengers" name="passengers" type="number" min="1" value="1" required></div><div class="mt-hotel-field"><label for="mt-suitcases">Maletas</label><input id="mt-suitcases" name="suitcases" type="number" min="0" value="0"></div><div class="mt-hotel-field"><label for="mt-carry_ons">Equipaje de mano</label><input id="mt-carry_ons" name="carry_ons" type="number" min="0" value="0"></div></div><button class="mt-hotel-primary-button" type="button" data-calculate>Calcular tarifa y vehículos</button><div class="mt-hnb-status" data-quote-status hidden></div></div>
<div class="mt-hotel-phase-card mt-hotel-field--full" data-results hidden><h2>2. Selecciona vehículo</h2><div class="mt-hnb-route-summary" data-route-summary></div><div class="mt-hnb-vehicles" data-vehicles></div></div>
<div class="mt-hotel-phase-card mt-hotel-field--full"><h2>3. Cliente</h2><div class="mt-hotel-form-grid"><div class="mt-hotel-field"><label for="mt-customer_name">Nombre</label><input id="mt-customer_name" name="customer_name" type="text" required></div><div class="mt-hotel-field"><label for="mt-customer_email">Email</label><input id="mt-customer_email" name="customer_email" type="email"></div><div class="mt-hotel-field"><label for="mt-customer_phone">Teléfono</label><input id="mt-customer_phone" name="customer_phone" type="text"></div><div class="mt-hotel-field"><label for="mt-flight_number">Nº de vuelo</label><input id="mt-flight_number" name="flight_number" type="text"></div><div class="mt-hotel-field mt-hotel-field--full"><label for="mt-notes">Notas</label><textarea id="mt-notes" name="notes" rows="4"></textarea></div></div></div>
<div class="mt-hotel-phase-card mt-hotel-field--full"><div class="mt-hnb-summary-body" data-final-summary>Calcula la ruta y selecciona un vehículo.</div><button class="mt-hotel-primary-button" type="submit" data-submit disabled>Crear reserva</button></div></form></section>
